export {
  CARDS_BAD_REQUEST,
  CARDS_NOT_FOUND_CARD,
  CARD_NOT_FOUND_ON_DELETE,
  LIKE_CARD_BAD_REQUEST,
  DISLIKE_CARD_BAD_REQUEST,
  USERS_CREATE_BAD_REQUEST,
  USERS_UPDATE_BAD_REQUEST,
  USERS_UPDATE_AVATAR_BAD_REQUEST,
  USERS_NOT_FOUND,
  SERVER_ERROR,
  NON_EXISTENT_ADDRESS,
} from './error-messages';
